<a href="https://colab.research.google.com/github/lnittala1-ops/BAN482/blob/main/BAN482_Python_for_Data_Science.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Python for Data Science

## Data Types in Python

### Lists

In [ ]:
import pandas as pd
 # Creating a list
sensor_readings = [25.5, 26.1, 24.9, 27.0]
sensor_readings

In [ ]:
# Lists can hold different data types
mixed_list = ['temperature', 28.3, True, 2023]
mixed_list

In [ ]:
# Accessing elements by index
# Note: Indexing from the front starts with 0
# Indexing from back starts with -1

print(mixed_list[0])
print(mixed_list[3])
print(sensor_readings[-1])

In [ ]:
# Mutability: Changing an element

# Example: Correcting a faulty reading
sensor_readings[2] = 25.2
sensor_readings

In [ ]:
# Adding elements
sensor_readings.append(27.5) # Add to the end
sensor_readings

In [ ]:
# Removing element by index
sensor_readings.pop(0) # Remove the first element
sensor_readings

In [ ]:
# Removing element by value
sensor_readings.remove(26.1)
sensor_readings

In [ ]:
# Example for adding two lists
list1 = ["Mercury", "Venus", "Earth"]
print(list1)
list2 = list1 + ["Mars", "Jupiter", "Saturn"]
print(list2)

In [ ]:
# Finding the number of elements in the list (or length)
len(list2)

### Tuple

In [ ]:
# Creating a tuple
coordinates = (34.0522, -118.2437) # (latitude, longitude)
coordinates

In [ ]:
# Tuples can also hold different data types
div_tuple = (255, False) # diverse tuple
div_tuple

In [ ]:
# Accessing elements by index (just like lists)
coordinates[0]

In [ ]:
# Immutability: Trying to change an element will cause an error
try:
    coordinates[0] = 34.1 # This line will raise a TypeError
except TypeError as e:
    print(f"Error trying to modify a tuple: {e}")

In [ ]:
# If you need to "change" a tuple, you create a new one
new_coordinates = (34.1000, coordinates[1])
new_coordinates

In [ ]:
# Named tuple example
from collections import namedtuple

Car = namedtuple('Car', ['make', 'model', 'price', 'horsepower', 'seats'])
chevyBlazer = Car('Chevrolet', 'Blazer', 32000, 275, 8)
chevyBlazer

### Set

In [ ]:
# Creating a set
data_tags = {'ml', 'python', 'data', 'ml'} # 'ml' appears twice but only stored once
data_tags

In [ ]:
# Sets are mutable: Adding and removing elements
data_tags.add('analytics')
data_tags

In [ ]:
# Removing from a set
data_tags.remove('python')
data_tags

In [ ]:
# Checking for membership (very efficient for sets)
'ml' in data_tags # Output: True

In [ ]:
# No indexing: This will cause an error
try:
    print(data_tags[0]) # This line will raise a TypeError
except TypeError as e:
    print(f"Error trying to index a set: {e}")

In [ ]:
# Finding unique elements from a list
student_ids = [101, 105, 102, 101, 103, 105]
unique_ids = set(student_ids)
print(student_ids)
print(unique_ids)

### Dictionary

In [ ]:
# Creating a dictionary
student_profile = {
    'name': 'Alice',
    'age': 20,
    'major': 'Computer Science',
    'gpa': 3.8
}
student_profile

In [ ]:
# Accessing values by key
student_profile['major'] # Output: Computer Science

In [ ]:
# Mutability: Changing and adding elements
student_profile['gpa'] = 3.9 # Update GPA
student_profile['university'] = 'Tech University' # Add a new field
student_profile

In [ ]:
# Removing elements
student_profile.pop('gpa')
student_profile

In [ ]:
# Iterating through a dictionary
print("Student profile details:")
for key, value in student_profile.items():
    print(f"  {key}: {value}")

# NumPy: Creating and Manipulating Arrays 🔢

This notebook demonstrates several fundamental NumPy functions for creating and manipulating arrays. These are core operations you'll use frequently in data science and machine learning.

First, we need to import the NumPy library.

In [ ]:
import numpy as np

---
## `np.array()`

This is the most fundamental way to create a NumPy array. You pass it a Python list or tuple, and it converts it into a high-performance NumPy `ndarray`.

In [ ]:
# Create a 1D array from a Python list
python_list = [1, 5, 2, 9]
my_array = np.array(python_list)

print("1D Array:")
print(my_array)
print(type(my_array))

1D Array:
[1 5 2 9]
<class 'numpy.ndarray'>

---
## `np.zeros()` and `np.ones()`

These are convenient shortcuts for creating arrays of a specific shape that are pre-filled with `0`s or `1`s. This is very common for initializing an array before you populate it with calculated data.

In [ ]:
# Create a 3x2 array of zeros
zeros_array = np.zeros(shape=(3, 2))
print("Zeros array:")
print(zeros_array)

# Create a 2x4 array of ones
ones_array = np.ones(shape=(2, 4))
print("\nOnes array:")
print(ones_array)

Zeros array:
[[0. 0.]
 [0. 0.]
 [0. 0.]]

Ones array:
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]

---
## `np.full()`

This is a more general version of `zeros` and `ones`. It allows you to create an array of a specific shape filled with any value you choose.

In [ ]:
# Create a 2x4 array where every element is the number 7
full_array = np.full(shape=(2, 4), fill_value=7)

print(full_array)

[[7 7 7 7]
 [7 7 7 7]]

---
## `np.insert()`

This function returns a **new array** with new values inserted at a specific position. The original array is not changed.

The `axis` parameter is key:
- **`axis=0`**: Inserts a new row.
- **`axis=1`**: Inserts a new column.

In [ ]:
# Define a 2x2 array
arr = np.array([[10, 20], [30, 40]])
print("Original Array:")
arr

Original Array:

array([[10, 20],
       [30, 40]])

In [ ]:
# Insert a new row with values [88, 88] at index 1
arr_new_rows = np.insert(arr, 1, [88, 88], axis=0)
print("\nAfter inserting a row:")
arr_new_rows

After inserting a row:

array([[10, 20],
       [88, 88],
       [30, 40]])

In [ ]:
# Insert a new column with values [99, 99] at index 0
arr_new_cols = np.insert(arr, 0, [99, 99], axis=1)
print("\nAfter inserting a column:")
arr_new_cols

---
## `np.delete()`

This function is the opposite of `insert`. It returns a **new array** with specified elements, rows, or columns removed. The original array is not changed.

The `axis` parameter is key:
- **`axis=0`**: Deletes a row.
- **`axis=1`**: Deletes a column.

In [ ]:
# Define a sample array
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("Original Array:")
print(arr)

Original Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

In [ ]:
# Delete the row at index 1 (the second row)
arr_new_rows = np.delete(arr, 1, axis=0)
print("\nAfter deleting row 1:")
print(arr_new_rows)

In [ ]:
# Delete the column at index 2 (the third column)
arr_new_cols = np.delete(arr, 2, axis=1)
print("\nAfter deleting column 2:")
print(arr_new_cols)

---
## `np.sort()`

This function returns a sorted copy of an array. You can control the sorting behavior with the `axis` parameter. The `axis` parameter tells NumPy the direction in which to "travel" or perform the operation. Think of it as the axis that gets "collapsed" or "traveled along."

`axis=1` (Sort ACROSS the columns): To sort along `axis=1`, NumPy keeps each row separate and sorts the values within that row from left to right. It travels across the columns for each row. This results in each row being sorted independently.

`axis=0` (Sort DOWN the rows): To sort along `axis=0`, NumPy keeps each column separate and sorts the values within that column from top to bottom. It travels down the rows for each column.

In summary:
- **`axis=1`** (default): Sorts each row independently.
- **`axis=0`**: Sorts each column independently.
- **`axis=None`**: Flattens the array into 1D, then sorts it.

In [ ]:
arr = np.array([[3, 1, 5], [2, 9, 4]])
print("Original Array:")
print(arr)

Original Array:
[[3 1 5]
 [2 9 4]]

In [ ]:
# Sort each row independently (along the last axis, axis=1)
sorted_rows = np.sort(arr, axis=1) # or just np.sort(arr)
print("\nSorted along rows (default):")
print(sorted_rows)

Sorted along rows (default):
[[1 3 5]
 [2 4 9]]

In [ ]:
# Sort each column independently (along axis=0)
sorted_cols = np.sort(arr, axis=0)
print("\nSorted along columns:")
print(sorted_cols)

Sorted along columns:
[[2 1 4]
 [3 9 5]]

In [ ]:
# Sort the flattened array
sorted_flat = np.sort(arr, axis=None)
print("\nSorted flat:")
print(sorted_flat)

Sorted flat:
[1 2 3 4 5 9]

# NumPy: Shape Manipulation Functions 📐

Code examples for key NumPy functions used to change an array's shape: `ravel()`, `reshape()`, `resize()`, and `transpose()`.

### Setup
Importing NumPy and creating a sample 2D array that we'll use for all the examples.

In [ ]:
import numpy as np

# A 2x3 array (2 rows, 3 columns)
arr = np.array([[0, 1, 2],
                [3, 4, 5]])

print("Original Sample Array:")
print(arr)

Original Sample Array:
[[0 1 2]
 [3 4 5]]

---
## `ravel()`

This function "flattens" a multi-dimensional array into a single, continuous 1D array. It's generally very fast because it usually returns a "view" of the original array's data without copying it.

In [ ]:
# Flatten the array into 1D using ravel()
raveled_arr = arr.ravel()

print("Raveled array:")
print(raveled_arr)

Raveled array:
[0 1 2 3 4 5]

---
## `reshape()`

This function gives the data a new shape without changing the data itself. The total number of elements in the new shape **must** be the same as the original.

In [ ]:
# The original array has 2*3 = 6 elements
print("Original 2x3 array (6 elements):")
print(arr)

# Reshape the 2x3 array into a 3x2 array (still 6 elements)
reshaped_arr = arr.reshape(3, 2)

print("\nReshaped to 3x2:")
print(reshaped_arr)

Original 2x3 array (6 elements):
[[0 1 2]
 [3 4 5]]

Reshaped to 3x2:
[[0 1]
 [2 3]
 [4 5]]

---
## `resize()`

The `np.resize()` function also changes an array's shape but is more flexible than `reshape()`. It **can** change the total number of elements.

- If the new shape is **larger**, the new array is filled with repeated copies of the original array's elements.
- If the new shape is **smaller**, the elements from the end are truncated.

**Note:** The function `np.resize(arr, ...)` returns a new array, while the method `arr.resize(...)` modifies the array in-place.

In [ ]:
print("Original 2x3 array (6 elements):")
print(arr)

# Resize to a LARGER 3x3 array (9 elements)
larger_arr = np.resize(arr, (3, 3))
print("\nResized to 3x3 (repeats elements):")
print(larger_arr)

# Resize to a SMALLER 2x2 array (4 elements)
smaller_arr = np.resize(arr, (2, 2))
print("\nResized to 2x2 (truncates elements):")
print(smaller_arr)

Original 2x3 array (6 elements):
[[0 1 2]
 [3 4 5]]

Resized to 3x3 (repeats elements):
[[0 1 2]
 [3 4 5]
 [0 1 2]]

Resized to 2x2 (truncates elements):
[[0 1]
 [2 3]]

---
## `transpose()` or `.T`

This operation flips the dimensions of an array. For a 2D matrix, it swaps the rows and columns. The `.T` attribute is a common and convenient shortcut for this.

In [ ]:
print("Original 2x3 array:")
print(arr)

# Transpose the array using the .transpose() method
transposed_arr = arr.transpose()
print("\nTransposed to 3x2 (using .transpose()):")
print(transposed_arr)

# The .T attribute is a more common and convenient way to do the same thing
print("\nTransposed to 3x2 (using .T):")
print(arr.T)

Original 2x3 array:
[[0 1 2]
 [3 4 5]]

Transposed to 3x2 (using .transpose()):
[[0 3]
 [1 4]
 [2 5]]

Transposed to 3x2 (using .T):
[[0 3]
 [1 4]
 [2 5]]

# Pandas: Subsetting Dataframes

Code examples for the different ways to select and subset data from a Pandas DataFrame:
1.  Selecting columns by their label (name).
2.  Selecting data by its integer position using `.iloc`.
3.  Selecting data by its label using `.loc`.
4.  The key difference in slicing behavior between `.iloc` and `.loc`.

### Setup

Import Pandas and create a sample DataFrame. We'll use country codes as custom index labels to better demonstrate the power of `.loc`.

In [ ]:
import pandas as pd

data = {
    'Country': ['USA', 'China', 'India', 'Brazil', 'Nigeria'],
    'Population': [331, 1441, 1393, 212, 206],
    'Continent': ['N. America', 'Asia', 'Asia', 'S. America', 'Africa']
}

# Use country codes as the index labels
index_labels = ['US', 'CN', 'IN', 'BR', 'NG']
country_df = pd.DataFrame(data, index = index_labels)

country_df

    Country  Population   Continent
US      USA         331  N. America
CN    China        1441        Asia
IN    India        1393        Asia
BR   Brazil         212  S. America
NG  Nigeria         206      Africa

---
## 1. Selecting Columns by Label

This is the most direct way to grab one or more columns.

- **Single Column:** Using `df['ColumnName']` returns a 1D **Series**.
- **Multiple Columns:** Using `df[['Col1', 'Col2']]` (with double brackets) returns a 2D **DataFrame**.

In [ ]:
# --- Select a single column (returns a Series) ---
population_series = country_df['Population']
print(population_series)
print(type(population_series))

US     331
CN    1441
IN    1393
BR     212
NG     206
Name: Population, dtype: int64
<class 'pandas.core.series.Series'>

In [ ]:
# --- Select multiple columns (returns a DataFrame) ---
multi_col_df = country_df[['Country', 'Continent']]
print(multi_col_df)
print(type(multi_col_df))

    Country   Continent
US      USA  N. America
CN    China        Asia
IN    India        Asia
BR   Brazil  S. America
NG  Nigeria      Africa
<class 'pandas.core.frame.DataFrame'>

---
## 2. Selecting by Integer Position (`.iloc`) 📍
Use **`.iloc`** (integer-location) when you want to select data based on its numerical position in the table (starting from 0).

**Key Point:** Slicing with `.iloc` is **exclusive** of the final index, just like in standard Python lists.

In [ ]:
# --- Select a single cell: Row 0, Column 1 ---
# This gets the Population of the first country
cell_value = country_df.iloc[0, 1]
print(f"--- Cell at [0, 1] ---\n{cell_value}\n")

--- Cell at [0, 1] ---
331

In [ ]:
# --- Select a single row: Row 2 (India) ---
india_row = country_df.iloc[2]
print("--- Row at index 2 ---")
print(india_row)

--- Row at index 2 ---
Country       India
Population     1393
Continent      Asia
Name: IN, dtype: object

In [ ]:
country_df

    Country  Population   Continent
US      USA         331  N. America
CN    China        1441        Asia
IN    India        1393        Asia
BR   Brazil         212  S. America
NG  Nigeria         206      Africa

In [ ]:
# --- Select a slice of rows and columns ---
# Rows 1 up to (but not including) 4
# Columns 0 up to (but not including) 2
data_slice = country_df.iloc[1:4, 0:2]
print("\n--- Slice [1:4, 0:2] ---")
print(data_slice)

--- Slice [1:4, 0:2] ---
   Country  Population
CN   China        1441
IN   India        1393
BR  Brazil         212

---
## 3. Selecting by Label (`.loc`) 🏷️

Use **`.loc`** (location) when you want to select data based on its index and column **labels**.

**Key Point:** Slicing with `.loc` is **inclusive** of the final label.

In [ ]:
# --- Select a single cell: Index 'US', Column 'Population' ---
cell_value_loc = country_df.loc['US', 'Population']
print(f"--- Cell at ['US', 'Population'] ---\n{cell_value_loc}\n")

--- Cell at ['US', 'Population'] ---
331

In [ ]:
# --- Select a single row by its index label 'IN' ---
india_row_loc = country_df.loc['IN']
print("--- Row with label 'IN' ---")
print(india_row_loc)

In [ ]:
# --- Select a slice of rows and specific columns by label ---
# Rows from label 'CN' through 'BR' (inclusive)
# Specific columns 'Population' and 'Continent'
data_slice_loc = country_df.loc['CN':'BR', ['Population', 'Continent']]
print("\n--- Slice ['CN':'BR', ['Population', 'Continent']] ---")
print(data_slice_loc)

---
## 4. `.iloc` vs. `.loc`: The Key Difference (Exclusive vs. Inclusive)

This is a common point of confusion. The most important difference is that **`.loc` slicing includes the last element**, while **`.iloc` slicing does not**.

In [ ]:
# .iloc is EXCLUSIVE: Gets rows at index 0 and 1. It *excludes* the end of the slice (2).
iloc_example = country_df.iloc[0:2]
print("--- .iloc[0:2] (Exclusive of 2) ---")
print(iloc_example)

In [ ]:
# .loc is INCLUSIVE: Gets rows from label 'US' through 'CN'. It *includes* the end of the slice ('CN').
loc_example = country_df.loc['US':'CN']
print("\n--- .loc['US':'CN'] (Inclusive of 'CN') ---")
print(loc_example)

# Pandas: Subsetting using Comparison Operators

Following code examples demonstrate the standard comparison operators in Python. First, we'll look at basic examples with variables, and then we'll see a practical application for filtering data in a Pandas DataFrame.

### Setup

Let's define a few variables to use in our basic examples.

In [ ]:
a = 15
b = 10
c = 15

---
## `==` (Equal to)
Checks if two values are exactly the same.

In [ ]:
# Returns True because a and c have the same value
print(f"Is {a} == {c}? {a == c}")

# Returns False because a and b have different values
print(f"Is {a} == {b}? {a == b}")

---
## `!=` (Not Equal to)
Checks if two values are different.

In [ ]:
# Returns True because a and b are different
print(f"Is {a} != {b}? {a != b}")

# Returns False because a and c are the same
print(f"Is {a} != {c}? {a != c}")

---
## `>` (Greater Than)
Checks if the value on the left is strictly greater than the value on the right.

In [ ]:
# Returns True because 15 is greater than 10
print(f"Is {a} > {b}? {a > b}")

# Returns False because 15 is not greater than 15
print(f"Is {a} > {c}? {a > c}")

---
## `>=` (Greater Than or Equal to)
Checks if the left value is greater than **or** equal to the right value.

In [ ]:
# Returns True because 15 is greater than 10
print(f"Is {a} >= {b}? {a >= b}")

# Returns True because 15 is equal to 15
print(f"Is {a} >= {c}? {a >= c}")

---
## `<` (Less Than)
Checks if the value on the left is strictly less than the value on the right.

In [ ]:
# Returns True because 10 is less than 15
print(f"Is {b} < {a}? {b < a}")

# Returns False because 15 is not less than 15
print(f"Is {a} < {c}? {a < c}")

---
## `<=` (Less Than or Equal to)
Checks if the left value is less than **or** equal to the right value.

In [ ]:
# Returns True because 10 is less than 15
print(f"Is {b} <= {a}? {b <= a}")

# Returns True because 15 is equal to 15
print(f"Is {a} <= {c}? {a <= c}")

---
## Practical Use: Filtering a Pandas DataFrame

In data science, the most common use for these operators is to filter dataframes. You create a condition that produces a series of `True`/`False` values (called a **boolean mask**), which you then use to select rows where the mask is `True`.

In [ ]:
import pandas as pd

data = {
    'Country': ['USA', 'China', 'India', 'Brazil', 'Nigeria'],
    'Population': [331, 1441, 1393, 212, 206],
    'Continent': ['N. America', 'Asia', 'Asia', 'S. America', 'Africa']
}
df = pd.DataFrame(data)

In [ ]:
# Example 1: Find all countries with a population greater than 300 million
# The expression df['Population'] > 300 creates the boolean mask
large_countries = df[df['Population'] > 300]
print("--- Countries with Population > 300M ---")
print(large_countries)

--- Countries with Population > 300M ---
  Country  Population   Continent
0     USA         331  N. America
1   China        1441        Asia
2   India        1393        Asia

In [ ]:
# Example 2: Find all countries in Asia with a population less than or equal to 1400 million
# We combine two boolean masks with the & (AND) operator
asian_countries = df[(df['Continent'] == 'Asia') & (df['Population'] <= 1400)]
print("\n--- Asian countries with Population <= 1400M ---")
print(asian_countries)

--- Asian countries with Population <= 1400M ---
  Country  Population Continent
2   India        1393      Asia

# Pandas: Common methods for Data Manipulation DataFrame Methods

Code examples for several common and powerful Pandas DataFrame methods for data manipulation. Following are covered:
- `.at[]`
- `.drop()`
- `.drop_duplicates()`
- `.dropna()`
- `.insert()`
- `.replace()`
- `.sort_values()`

### Setup

Import the necessary libraries and create a sample DataFrame. This DataFrame includes duplicate rows, missing values, and varied data types, which will help demonstrate the functionality of each method.

In [ ]:
import pandas as pd
import numpy as np

# Create a sample DataFrame
data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Charlie', 'Eve', 'Frank'],
    'Major': ['CompSci', 'Biology', 'Business', 'Art', 'Business', np.nan, 'CompSci'],
    'Score': [95, 88, 76, np.nan, 76, 91, 85],
    'Grad_Year': [2024, 2025, 2024, 2025, 2024, 2025, 2024]
}
student_ids = ['S01', 'S02', 'S03', 'S04', 'S05', 'S06', 'S07']
df = pd.DataFrame(data, index=student_ids)

print("--- Original DataFrame ---")
df

--- Original DataFrame ---

        Name     Major  Score  Grad_Year
S01    Alice   CompSci   95.0       2024
S02      Bob   Biology   88.0       2025
S03  Charlie  Business   76.0       2024
S04    David       Art    NaN       2025
S05  Charlie  Business   76.0       2024
S06      Eve       NaN   91.0       2025
S07    Frank   CompSci   85.0       2024

---
## `.at[]`

This method provides fast, label-based access to a **single value** in a DataFrame. It is more performant than using `.loc` for accessing a single element.

In [ ]:
# Get the score for the student with index 'S02'
bob_score = df.at['S02', 'Score']

print(f"Bob's score is: {bob_score}")

---
## `.drop()`

This removes specified rows or columns from the DataFrame. By default, it returns a new DataFrame without modifying the original.

In [ ]:
# --- Drop rows by index label ---
# Note: axis=0 refers to rows (the default)
df_no_rows = df.drop(labels=['S03', 'S05'], axis=0)
print("--- DataFrame after dropping rows S03 and S05 ---")
print(df_no_rows)

--- DataFrame after dropping rows S03 and S05 ---
      Name    Major  Score  Grad_Year
S01  Alice  CompSci   95.0       2024
S02    Bob  Biology   88.0       2025
S04  David      Art    NaN       2025
S06    Eve      NaN   91.0       2025
S07  Frank  CompSci   85.0       2024

In [ ]:
# --- Drop a column by its label ---
# Note: axis=1 refers to columns. Using the `columns` parameter is often clearer.
df_no_cols = df.drop(columns='Grad_Year')
print("\n--- DataFrame after dropping the 'Grad_Year' column ---")
print(df_no_cols)

---
## `.drop_duplicates()`

This removes duplicate rows from the DataFrame. You can consider all columns for duplication or just a specific subset.

In [ ]:
# --- Drop duplicates based on all columns ---
# The second 'Charlie' row (index S05) is a complete duplicate of the one at S03
df_no_dupes = df.drop_duplicates()
print("--- DataFrame after dropping full duplicates ---")
print(df_no_dupes)

In [ ]:
# --- Drop duplicates based on a subset of columns ---
# This will keep the first instance of each major, removing the second 'Business' and 'CompSci' rows
df_unique_majors = df.drop_duplicates(subset=['Major'])
print("\n--- DataFrame after dropping duplicates in the 'Major' column ---")
print(df_unique_majors)

--- DataFrame after dropping duplicates in the 'Major' column ---
        Name     Major  Score  Grad_Year
S01    Alice   CompSci   95.0       2024
S02      Bob   Biology   88.0       2025
S03  Charlie  Business   76.0       2024
S04    David       Art    NaN       2025
S06      Eve       NaN   91.0       2025

---
## `.dropna()`

This removes rows or columns that contain missing values (`NaN`).

In [ ]:
# --- Drop any row containing at least one NaN value ---
# This will remove the rows for David (score is NaN) and Eve (major is NaN)
df_no_na = df.dropna()
print("--- DataFrame after dropping all rows with any NaN ---")
print(df_no_na)

In [ ]:
# --- Drop rows where NaN appears only in specific columns ---
# This will only drop the row for David, because Eve's score is not NaN
df_no_na_subset = df.dropna(subset=['Score'])
print("\n--- DataFrame after dropping rows with NaN only in the 'Score' column ---")
print(df_no_na_subset)

---
## `.insert()`

This adds a new column to the DataFrame at a specified integer location. Unlike most other methods, this method modifies the DataFrame **in-place** and does not return a new object.

In [ ]:
# Create a copy to avoid modifying the original df for the next examples
df_inserted = df.copy()

# Insert a new column 'On_Probation' at index position 2
# Note: loc=2 means it will be the 3rd column
on_probation_values = [False, False, True, False, True, False, False]
df_inserted.insert(loc=2, column='On_Probation', value=on_probation_values)

print("--- DataFrame after inserting a new column ---")
print(df_inserted)

---
## `.replace()`

This method replaces specified values in the DataFrame with new values.

In [ ]:
# --- Replace a single value with another ---
df_replaced = df.replace(to_replace='CompSci', value='Computer Science')
print("--- DataFrame after replacing 'CompSci' ---")
print(df_replaced)

In [ ]:
# --- Replace multiple values using a dictionary ---
df_multi_replaced = df.replace({'Business': 'B.A.', 'Biology': 'B.S.'})
print("\n--- DataFrame after replacing multiple values ---")
print(df_multi_replaced)

---
## `.sort_values()`

This sorts the DataFrame by the values in one or more columns.

In [ ]:
# --- Sort by a single column (Score) in ascending order ---
df_sorted_score = df.sort_values(by='Score')
print("--- DataFrame sorted by Score (ascending) ---")
print(df_sorted_score)

In [ ]:
# --- Sort by multiple columns ---
# Sort by Grad_Year (ascending), then by Score within each year (descending)
df_multi_sorted = df.sort_values(by=['Grad_Year', 'Score'], ascending=[True, False])
print("\n--- DataFrame sorted by Grad_Year (asc) and Score (desc) ---")
print(df_multi_sorted)

# Data Wrangling

In [ ]:
# create a dataframe with 4 columns. Airline, Origin city, Destination city, Price of ticket, distance in kilometers
import pandas as pd

In [ ]:
# Import Data
college_coffee = pd.read_csv('college_coffee.csv')

In [ ]:
# View high level structure of the dataframe using the .info() method
college_coffee.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   major               10 non-null     object
 1   study_hours_weekly  8 non-null      float64
 2   coffee_consumed_oz  9 non-null      float64
 3   avg_grade_percent   10 non-null     object
dtypes: float64(2), object(2)
memory usage: 452.0+ bytes

In [ ]:
# Display dataframe
college_coffee

              major  study_hours_weekly  coffee_consumed_oz avg_grade_percent
0  Computer Science                25.0                64.0             "91%"
1        Psychology                18.0                48.0            "88 %"
2       Engineering                30.0                 NaN             "85%"
3           English                15.0                32.0             "94%"
4           Biology                 NaN                80.0            "89 %"
5          Business                20.0               100.0             "90%"
6       Art History                12.0                24.0            "97 %"
7           Nursing                28.0                72.0             "92%"
8       Mathematics                 NaN                50.0             "95%"
9           Pre-Med                35.0                96.0            "87 %"

In [ ]:
# Remove rows with missing values
college_coffee = college_coffee.dropna()
college_coffee

              major  study_hours_weekly  coffee_consumed_oz avg_grade_percent
0  Computer Science                25.0                64.0             "91%"
1        Psychology                18.0                48.0            "88 %"
3           English                15.0                32.0             "94%"
5          Business                20.0               100.0             "90%"
6       Art History                12.0                24.0            "97 %"
7           Nursing                28.0                72.0             "92%"
9           Pre-Med                35.0                96.0            "87 %"

In [ ]:
# Convert coffee consumed to grams
college_coffee['coffee_consumed_grams'] = college_coffee['coffee_consumed_oz'] * 28.3495
display(college_coffee)

,major,study_hours_weekly,coffee_consumed_oz,avg_grade_percent,coffee_consumed_grams
0,Computer Science,25.0,64.0,"""91%""",1814.368
1,Psychology,18.0,48.0,"""88 %""",1360.776
3,English,15.0,32.0,"""94%""",907.184
5,Business,20.0,100.0,"""90%""",2834.950
6,Art History,12.0,24.0,"""97 %""",680.388
7,Nursing,28.0,72.0,"""92%""",2041.164
9,Pre-Med,35.0,96.0,"""87 %""",2721.552

In [ ]:
# Change name to study hours per week
college_coffee.rename(columns={'study_hours_weekly':'study_hours'}, inplace=True)
display(college_coffee)

,major,study_hours,coffee_consumed_oz,avg_grade_percent,coffee_consumed_grams
0,Computer Science,25.0,64.0,"""91%""",1814.368
1,Psychology,18.0,48.0,"""88 %""",1360.776
3,English,15.0,32.0,"""94%""",907.184
5,Business,20.0,100.0,"""90%""",2834.950
6,Art History,12.0,24.0,"""97 %""",680.388
7,Nursing,28.0,72.0,"""92%""",2041.164
9,Pre-Med,35.0,96.0,"""87 %""",2721.552

In [ ]:
# Import college data file
college_data = pd.read_csv('college_data.csv')

In [ ]:
college_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 6 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Major                   10 non-null     object
 1   Favorite Subject        10 non-null     object
 2   Study Group             10 non-null     object
 3   Campus Location         10 non-null     object
 4   Hours Studied Per Week  10 non-null     int64
 5   Cups of Coffee Per Day  10 non-null     int64
dtypes: int64(2), object(4)
memory usage: 612.0+ bytes

In [ ]:
college_data

,Major,Favorite Subject,Study Group,Campus Location,Hours Studied Per Week,Cups of Coffee Per Day
0,Art History,History,Yes,South Campus,21,0
1,English,English,Yes,North Campus,29,2
2,Biology,Math,Yes,Online,35,2
3,Mathematics,English,No,North Campus,35,3
4,English,Science,No,North Campus,5,0
5,Business,Art,Yes,North Campus,20,0
6,Engineering,Art,No,Online,13,0
7,English,History,No,North Campus,18,0
8,Pre-Med,History,Yes,North Campus,14,0
9,Computer Science,Art,Yes,Online,22,1

## Tutorial: Using `.pivot_table()` for Data Aggregation

The `.pivot_table()` method in pandas is a powerful tool for summarizing and aggregating data in a DataFrame. It allows you to restructure your data based on one or more key columns and apply various aggregation functions.

**Basic Syntax:**

In [ ]:
# Example using .pivot_table() with college_data

# Calculate the average hours studied per week for each major
average_study_hours = college_data.pivot_table(values='Hours Studied Per Week', columns = 'Campus Location',index='Major', aggfunc='mean')
average_study_hours

Campus Location   North Campus  Online  South Campus
Major
Art History                NaN     NaN          21.0
Biology                    NaN    35.0           NaN
Business             20.000000     NaN           NaN
Computer Science           NaN    22.0           NaN
Engineering                NaN    13.0           NaN
English              17.333333     NaN           NaN
Mathematics          35.000000     NaN           NaN
Pre-Med              14.000000     NaN           NaN

**Class Exercises:**

In [ ]:
# Calculate the total cups of coffee consumed per day for each campus location
total_coffee_cups = college_data.pivot_table(values='Cups of Coffee Per Day', index='Campus Location', aggfunc='sum')
display(total_coffee_cups)

                 Cups of Coffee Per Day
Campus Location
North Campus                          5
Online                                3
South Campus                          0

In [ ]:
# Calculate the count of students in each major and study group combination
student_count = college_data.pivot_table(index='Major', columns='Study Group', aggfunc='size', fill_value=0)
# fill_value argument can be used to for contingencies when there is no existing data
student_count

Student count by Major and Study Group:

Study Group        No  Yes
Major
Art History       NaN  1.0
Biology           NaN  1.0
Business          NaN  1.0
Computer Science  NaN  1.0
Engineering       1.0  NaN
English           2.0  1.0
Mathematics       1.0  NaN
Pre-Med           NaN  1.0

In [ ]:
# Calculate the average hours studied and total coffee cups for each major
agg_functions = {'Hours Studied Per Week': 'mean', 'Cups of Coffee Per Day': 'sum'}
# This is one way to include different aggregation functions on different columns
aggregated_data = college_data.pivot_table(index='Major', aggfunc=agg_functions)
aggregated_data

Average study hours and total coffee cups by Major:

                  Cups of Coffee Per Day  Hours Studied Per Week
Major
Art History                            0               21.000000
Biology                                2               35.000000
Business                               0               20.000000
Computer Science                       1               22.000000
Engineering                            0               13.000000
English                                2               17.333333
Mathematics                            3               35.000000
Pre-Med                                0               14.000000

## Tutorial: Using `.groupby()` for Data Aggregation

The `.groupby()` method in pandas is used to group rows of a DataFrame together based on one or more columns and then perform calculations on those groups. It's a fundamental step in data analysis for summarizing and aggregating data.

**Basic Concept:**

1. **Splitting:** The data is split into groups based on the unique values in the specified column(s).
2. **Applying:** A function (like aggregation, transformation, or filtering) is applied to each group.
3. **Combining:** The results from each group are combined into a new DataFrame or Series.

**Basic Syntax:**

In [ ]:
# Example using .groupby() with college_data

# Calculate the average hours studied per week for each major
average_study_hours_groupby = college_data.groupby('Major')['Hours Studied Per Week'].mean()
average_study_hours_groupby

Major
Art History         21.000000
Biology             35.000000
Business            20.000000
Computer Science    22.000000
Engineering         13.000000
English             17.333333
Mathematics         35.000000
Pre-Med             14.000000
Name: Hours Studied Per Week, dtype: float64

**Class Exercises:**

In [ ]:
# Calculate the total cups of coffee consumed per day for each campus location
total_coffee_cups_groupby = college_data.groupby('Campus Location')['Cups of Coffee Per Day'].sum()
total_coffee_cups_groupby

Campus Location
North Campus    5
Online          3
South Campus    0
Name: Cups of Coffee Per Day, dtype: int64

In [ ]:
# Calculate the count of students in each major

In [ ]:
# Calculate the average hours studied and total coffee cups for each major